### ISSUE TITLE
Dynamics 365 enterprise license Product List incorrect 

### ISSUE THREAD

**Issue by mehtaronak12** [MicrosoftDocs/customer-voice#63] opened 2022-06-06 06:40 UTC
Dear Team,

The list of related D365 Enterprise licenses includes Project Ops however license guide does not include project opts. Kindly let me know if customer voice is included with D365 Project ops. 
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb076b68-c826-103a-617e-0d3a54295977
* Version Independent ID: 1a0830d6-601a-2e0b-c3f3-886dd4c31c70
* Content: [Purchase Dynamics 365 Customer Voice and additional license](https://docs.microsoft.com/en-gb/dynamics365/customer-voice/purchase#feedback)
* Content Source: [cv-docs/purchase.md](https://github.com/MicrosoftDocs/customer-voice/blob/main/cv-docs/purchase.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by bishalgoswami** [comment] 2022-06-06 07:00
Thanks for your comment, @mehtaronak12. This issue has been assigned to the doc author for review.

**Comment by sbmjais** [comment] 2024-02-08 14:07
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by sbmjais** 2024-02-08 14:07 UTC
Labels: assigned-to-author
